### ISSUE TITLE
Deleting a train doesn't auto update other sessions.

### ISSUE THREAD

**Issue by nicovanrensburg** [valfragier16/Train-Scheduler#1]
When adding a train with two tabs open it adds correctly to the second tab

When removing a train with the trash button it doesn't auto delete off the second tab.

How would you approach fixing this? @valfragier16

**Comment by valfragier16** [comment]
Hi Nico, can you please clarify what you are asking? I think you are stating that the time updates when another train is added to the schedule but when a train entry is deleted it does not update the time of the train entry that is left on the schedule. Is this what you are asking?
